name: airkiss_dart
version: 1.0.0+3
description: A dart airkiss lib.
homepage: https://github.com/OpenIoTHub/airkiss_dart
documentation: https://github.com/OpenIoTHub/airkiss_dart
environment:
  sdk: ^3.0.0