name: airkiss_dart
version: 1.0.0
description: A dart airkiss lib.
homepage: https://github.com/OpenIoTHub/dart_airkiss
documentation: https://github.com/OpenIoTHub/dart_airkiss
environment:
  sdk: ^3.0.0
publish_to: https://pub.dartlang.org
